/**
 * HED vocabulary bundle access and search (website#255).
 *
 * The bundle itself (`hed-vocab.json`, ~341 KB — every non-deprecated base-HED
 * and HED-SCORE tag, website#269) is generated by
 * `scripts/extract-hed-vocab.mjs` and reached only through `loadHedVocab`'s
 * dynamic import, so Vite splits it into its own chunk. The viewer's initial
 * bundle therefore never carries it: the fetch happens the first time somebody
 * turns annotation mode on, and the result is memoized for the life of the
 * page.
 *
 * The search is hand-rolled for the same reason the charts are: it is forty
 * lines of scoring over the bundle's entries (1525 at HED 8.4.0 + SCORE
 * 2.1.0), which no dependency improves. It is also pure, so it is unit-tested
 * against the real bundle shape rather than through the DOM.
 */

export interface HedVocabEntry {
  /** Short form: the bare leaf tag, e.g. "Epileptic-seizure". */
  tag: string;
  /**
   * Long form, library prefix included: the bundle's identity for a tag and
   * the key annotations store and look up by. NOT what an export writes —
   * `hedShortForm` derives the short form for the file (website#268).
   */
  path: string;
  description: string;
  /** "HED8.4.0" or "SCORE2.1.0". */
  schema: string;
}

export interface HedSchemaRef {
  id: string;
  name: string;
  version: string;
  /** HED library namespace prefix ("sc" for SCORE), "" for the standard schema. */
  prefix: string;
}

export interface HedQuickPickGroup {
  group: string;
  /** Long-form paths, resolvable against `entries`. */
  paths: string[];
}

export interface HedVocab {
  bundleVersion: number;
  schemas: HedSchemaRef[];
  quickPicks: HedQuickPickGroup[];
  entries: HedVocabEntry[];
}

let cached: Promise<HedVocab> | null = null;

/**
 * Load (once) the vocabulary bundle. Deliberately the only reference to the
 * JSON in the codebase — anything else importing it statically would pull
 * ~341 KB into whichever chunk did so.
 */
export function loadHedVocab(): Promise<HedVocab> {
  if (!cached) {
    cached = import("./hed-vocab.json").then((m) => (m.default ?? m) as unknown as HedVocab);
  }
  return cached;
}

/** The `HEDVersion` value a sidecar needs for the tags this bundle offers. */
export function hedVersionSpec(vocab: HedVocab): string[] {
  return vocab.schemas.map((s) =>
    s.prefix ? `${s.prefix}:${s.name}_${s.version}` : `${s.version}`,
  );
}

export function entriesByPath(vocab: HedVocab): Map<string, HedVocabEntry> {
  return new Map(vocab.entries.map((e) => [e.path, e]));
}

/**
 * Quick picks for a *channel* annotation: the noise and artifact vocabulary,
 * and only that.
 *
 * A channel-scoped statement is almost never "this electrode had a seizure" —
 * it is "this electrode was noisy, flat, popping, drifting". So the bundle's
 * general quick picks (epileptiform, sleep) are the wrong offer here, and the
 * annotator would have to search past them every time. These groups are
 * derived from the bundle rather than curated separately, so a regenerated
 * bundle keeps them in step with no second list to maintain.
 *
 * Base HED's artifact tree carries the causes (`Eye-blink-artifact`,
 * `Line-noise-artifact`); SCORE contributes how much the artifact cost the
 * recording. Groups come out in that order, and an empty one is dropped.
 */
export function artifactQuickPicks(vocab: HedVocab): HedQuickPickGroup[] {
  const isArtifact = (e: HedVocabEntry): boolean => e.path.toLowerCase().includes("artifact");
  const base = vocab.entries.filter((e) => isArtifact(e) && !e.path.startsWith("sc:"));
  const groups: HedQuickPickGroup[] = [
    {
      group: "Artifact",
      paths: base
        .filter(
          (e) =>
            !e.path.includes("/Biological-artifact") && !e.path.includes("/Nonbiological-artifact"),
        )
        .map((e) => e.path),
    },
    {
      group: "Biological",
      paths: base.filter((e) => e.path.includes("/Biological-artifact")).map((e) => e.path),
    },
    {
      group: "Non-biological",
      paths: base.filter((e) => e.path.includes("/Nonbiological-artifact")).map((e) => e.path),
    },
    {
      group: "Effect on the recording",
      paths: vocab.entries
        .filter((e) => isArtifact(e) && e.path.startsWith("sc:"))
        .map((e) => e.path),
    },
  ];
  return groups.filter((g) => g.paths.length > 0);
}

// --- search ----------------------------------------------------------------

export interface HedSearchResult {
  entry: HedVocabEntry;
  score: number;
}

/**
 * Score one entry against a lowercased query. Higher is better; 0 means "no
 * match, do not show". The tiers are ordered by how confidently a hit predicts
 * intent:
 *
 *  - the whole query is the tag                      exact
 *  - the tag starts with the query                   prefix
 *  - a hyphen-delimited word of the tag starts with it   word boundary
 *  - the tag contains it anywhere                    substring
 *  - the long-form path contains it (an ancestor matched)
 *  - the description contains it                     last resort
 *
 * Word-boundary beats bare substring because HED tags are hyphenated compounds
 * ("Eye-blink-artifact"), so "blink" hitting a word start is a much stronger
 * signal than "ink" hitting the middle of one. Shorter tags win ties: a query
 * that matches both "Spike" and "Runs-of-rapid-spikes" almost always meant the
 * first.
 */
export function scoreVocabEntry(entry: HedVocabEntry, query: string): number {
  if (query === "") return 0;
  const tag = entry.tag.toLowerCase();
  const brevity = 1 / (1 + tag.length / 40);

  if (tag === query) return 1000 + brevity;
  if (tag.startsWith(query)) return 800 + brevity;
  if (tag.split("-").some((word) => word.startsWith(query))) return 600 + brevity;
  const inTag = tag.indexOf(query);
  if (inTag >= 0) return 400 + brevity - inTag / 1000;

  const path = entry.path.toLowerCase();
  if (path.includes(query)) return 200 + brevity;

  if (entry.description.toLowerCase().includes(query)) return 100 + brevity;
  return 0;
}

/**
 * Best matches for a query, highest score first. Ties break on the entries'
 * own (schema, path) order, which the bundle is already sorted by, so the same
 * query always produces the same list.
 *
 * A multi-word query ("eye blink") is treated as a conjunction: every term has
 * to match somewhere, and the entry scores as its weakest term. That keeps
 * "eye blink" from ranking an entry that matches only "eye" above the one that
 * matches both.
 */
export function searchVocab(
  entries: HedVocabEntry[],
  query: string,
  limit = 40,
): HedSearchResult[] {
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return [];
  const out: HedSearchResult[] = [];
  for (const entry of entries) {
    let worst = Number.POSITIVE_INFINITY;
    for (const term of terms) {
      const score = scoreVocabEntry(entry, term);
      if (score === 0) {
        worst = 0;
        break;
      }
      if (score < worst) worst = score;
    }
    if (worst > 0) out.push({ entry, score: worst });
  }
  // Stable sort (ES2019+) over an already-ordered input, so equal scores keep
  // the bundle's deterministic order.
  out.sort((a, b) => b.score - a.score);
  return out.slice(0, limit);
}
